Demo, CI: add fallback sources, test fallback
vitaut/modules pull request #13
Opened 2023-04-23 12:47 UTC by Mixaill

Part of #2 
Requires #11 

* move example to the subfolder to make repo root a bit more cleaner
* add fallback sources
* add C++14 and C++17 to the CI
* test demo output in CI

2023-04-27 14:55 UTC, vitaut requested changes

2023-04-27 14:55 UTC, vitaut commented on .github/workflows/linux.yml
> +        standard: [14, 17, 20, 23]
I don't think we need to test 14 because the only interesting transition happens at 17 -> 20 when modules become available.

2023-04-27 14:55 UTC, vitaut commented on .github/workflows/linux.yml
> +        CHECK_STRING: ${{fromJSON('["Modules are late to the party :(", "Hello, modules!"]')[matrix.standard > 17]}}
clever =)

2023-04-27 14:55 UTC, vitaut commented on example/helloworld/CMakeLists.txt
> +include(../../modules.cmake)
I don't think we need such a deep nesting. One level should be enough, i.e. let's merge example/helloworld into example.

2023-04-27 21:07 UTC, Mixaill commented on .github/workflows/linux.yml
> +        standard: [14, 17, 20, 23]
removed

2023-04-27 21:09 UTC, Mixaill commented on .github/workflows/linux.yml
> +        CHECK_STRING: ${{fromJSON('["Modules are late to the party :(", "Hello, modules!"]')[matrix.standard > 17]}}
have to be smart because not all DSLs reach CMake perfection.

2023-04-27 21:09 UTC, Mixaill commented on example/helloworld/CMakeLists.txt
> +include(../../modules.cmake)
moved

2023-04-27 21:09 UTC, Mixaill commented
@vitaut issues addressed

2023-04-29 12:47 UTC, vitaut approved these changes

2023-04-29 12:47 UTC, merged

2023-04-29 12:47 UTC, vitaut commented
Thank you!